# Label any PR whose branch starts with 'infect-' as 'feature'
feature:
  - head-branch:
    - '^infect-'

# Label 'phage-*' branches as 'bug'
bug:
  - head-branch:
    - '^phage-'

# Label 'mutagen-*' branches as 'experimental'
experimental:
  - head-branch:
    - '^mutagen-'

# Label 'autoclave-*' branches as 'refactor'
refactor:
  - head-branch:
    - '^autoclave-'

# Label 'triage-*' branches as 'hotfix'
hotfix:
  - head-branch:
    - '^triage-'
