#!/bin/bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3
MSG=$(cat $COMMIT_MSG_FILE)

# /usr/bin/perl -i.bak -ne 'print unless(m/^. Please enter the commit message/..m/^#$/)' "$COMMIT_MSG_FILE"

#!/bin/bash

# Skip merge commits
if [[ "$2" == "merge" ]] || [[ "$2" == "squash" ]]; then
  exit 0
fi

# DEFAULT_PREFIX="🧪 mutate: "

MSG_FILE=$1
MSG=$(cat $MSG_FILE)

# # Only add default prefix if no emoji found
# if ! grep -qE "^(\p{So}|\p{Sk}|\p{Sm}|\p{Sc})" <<< "$MSG"; then
#   echo "${DEFAULT_PREFIX}${MSG}" > $MSG_FILE
# fi


case "$COMMIT_SOURCE,$SHA1" in
 ,|template,)
   /usr/bin/perl -i.bak -pe '
      print "\n" . `git diff --cached --name-status -r`
	 if /^#/ && $first++ == 0' "$COMMIT_MSG_FILE" ;;
 *) ;;
esac
